# Generated by Django 3.0 on 2020-09-26 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200912_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='images/'),
            preserve_default=False,
        ),
    ]
