# Generated by Django 3.0 on 2020-10-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200926_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='model_pic',
            field=models.ImageField(default='none/no-img.jpg', upload_to=''),
        ),
    ]
