# Generated by Django 3.0 on 2020-11-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_register_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
