# Generated by Django 3.0 on 2020-11-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_remove_register_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='model_pic',
        ),
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(default='none/no-img.jpg', upload_to=''),
        ),
    ]
